-- GUCHIの歴史添削隊 v6.2
-- GitHub Pages + Supabase 共有運用用
--
-- 役割
--   先生: Supabase Auth の通常ユーザー（メール+パスワード）
--   生徒: Supabase Auth の匿名ユーザー + 名前/ログインコードで紐付け
--
-- 注意
--   Secret key / service_role key はブラウザに置かないでください。
--   このSQLを Supabase Dashboard > SQL Editor で実行してください。

create extension if not exists pgcrypto;

-- =========================================================
-- Tables
-- =========================================================

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  subject text not null default 'japanese' check (subject in ('japanese','world')),
  title text not null,
  theme text,
  goal text,
  method text,
  source text,
  prompt text not null,
  char_limit integer not null default 50 check (char_limit between 1 and 2000),
  min_ratio numeric not null default 0.8,
  before_fields jsonb not null default '[]'::jsonb,
  required_elements jsonb not null default '[]'::jsonb,
  answer_flow text,
  teacher_model text,
  worksheet_pdf_path text,
  worksheet_pdf_name text,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  subjects text[] not null default array['japanese','world']::text[],
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ログインコードは生徒本人からも直接読めない別テーブルに分離
create table if not exists public.student_secrets (
  student_id uuid primary key references public.students(id) on delete cascade,
  login_code text not null,
  updated_at timestamptz not null default now()
);

-- 生徒1人を複数端末から使えるよう、匿名Authユーザーとの紐付けを端末単位で保持
create table if not exists public.student_devices (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.students(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(auth_user_id)
);
create index if not exists student_devices_student_id_idx on public.student_devices(student_id);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  before_answers jsonb not null default '[]'::jsonb,
  own_required jsonb not null default '[]'::jsonb,
  own_flow text,
  answer_image_path text,
  ai_transcript_raw text,
  answer text,
  self_checks jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft','submitted','returned')),
  feedback jsonb,
  rewrite text,
  rewrite_submitted_at timestamptz,
  submitted_at timestamptz,
  returned_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (assignment_id, student_id)
);

-- =========================================================
-- Helper functions for RLS
-- =========================================================

create or replace function public.is_teacher()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false;
$$;

create or replace function public.current_student_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select sd.student_id
  from public.student_devices sd
  where sd.auth_user_id = auth.uid()
  limit 1;
$$;

grant execute on function public.is_teacher() to authenticated;
grant execute on function public.current_student_id() to authenticated;

-- =========================================================
-- RLS
-- =========================================================

alter table public.assignments enable row level security;
alter table public.students enable row level security;
alter table public.student_secrets enable row level security;
alter table public.student_devices enable row level security;
alter table public.submissions enable row level security;

-- Signed-out visitors should not read/write app tables.
revoke all on public.assignments from anon;
revoke all on public.students from anon;
revoke all on public.student_secrets from anon;
revoke all on public.student_devices from anon;
revoke all on public.submissions from anon;

-- Authenticated users need operation grants; RLS below restricts rows by role.
grant select, insert, update, delete on public.assignments to authenticated;
grant select, insert, update, delete on public.students to authenticated;
grant select, insert, update, delete on public.student_secrets to authenticated;
grant select, insert, update, delete on public.student_devices to authenticated;
grant select, insert, update, delete on public.submissions to authenticated;

-- assignments
 drop policy if exists "teacher full assignments" on public.assignments;
create policy "teacher full assignments"
on public.assignments for all to authenticated
using (public.is_teacher())
with check (public.is_teacher());

drop policy if exists "student read published assignments" on public.assignments;
create policy "student read published assignments"
on public.assignments for select to authenticated
using (
  not public.is_teacher()
  and published = true
  and exists (
    select 1 from public.students s
    where s.id = public.current_student_id()
      and s.active = true
      and assignments.subject = any(s.subjects)
  )
);

-- students
 drop policy if exists "teacher full students" on public.students;
create policy "teacher full students"
on public.students for all to authenticated
using (public.is_teacher())
with check (public.is_teacher());

drop policy if exists "student read self" on public.students;
create policy "student read self"
on public.students for select to authenticated
using (id = public.current_student_id());

-- student_secrets: teacher only. student-login Edge Function uses server-side secret key and bypasses RLS.
 drop policy if exists "teacher full student secrets" on public.student_secrets;
create policy "teacher full student secrets"
on public.student_secrets for all to authenticated
using (public.is_teacher())
with check (public.is_teacher());


-- Edge Function server-side privileges (student-login)
grant usage on schema public to service_role;
grant select on table public.students to service_role;
grant select on table public.student_secrets to service_role;
grant select, insert, update, delete on table public.student_devices to service_role;
grant usage, select on sequence public.student_devices_id_seq to service_role;

-- student_devices: teacher can inspect/delete. Edge Function creates mappings with server-side secret key.
 drop policy if exists "teacher full student devices" on public.student_devices;
create policy "teacher full student devices"
on public.student_devices for all to authenticated
using (public.is_teacher())
with check (public.is_teacher());

-- submissions
 drop policy if exists "teacher full submissions" on public.submissions;
create policy "teacher full submissions"
on public.submissions for all to authenticated
using (public.is_teacher())
with check (public.is_teacher());

drop policy if exists "student read own submissions" on public.submissions;
create policy "student read own submissions"
on public.submissions for select to authenticated
using (
  student_id = public.current_student_id()
  and exists (select 1 from public.students s where s.id = public.current_student_id() and s.active = true)
);

drop policy if exists "student insert own submissions" on public.submissions;
create policy "student insert own submissions"
on public.submissions for insert to authenticated
with check (
  student_id = public.current_student_id()
  and status in ('draft','submitted')
  and exists (
    select 1 from public.assignments a
    join public.students s on s.id = public.current_student_id()
    where a.id = submissions.assignment_id
      and a.published = true
      and s.active = true
      and a.subject = any(s.subjects)
  )
);

drop policy if exists "student update own submissions" on public.submissions;
create policy "student update own submissions"
on public.submissions for update to authenticated
using (
  student_id = public.current_student_id()
  and exists (select 1 from public.students s where s.id = public.current_student_id() and s.active = true)
)
with check (student_id = public.current_student_id());

-- Anonymous students may edit their own learning fields, but may not forge teacher feedback/return state.
create or replace function public.protect_submission_teacher_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_teacher() then
    return new;
  end if;

  if new.student_id is distinct from old.student_id
     or new.assignment_id is distinct from old.assignment_id
     or new.feedback is distinct from old.feedback
     or new.returned_at is distinct from old.returned_at then
    raise exception 'teacher-owned submission fields cannot be changed by students';
  end if;

  if new.status = 'returned' then
    raise exception 'students cannot mark a submission as returned';
  end if;

  return new;
end;
$$;

drop trigger if exists protect_submission_teacher_fields_trigger on public.submissions;
create trigger protect_submission_teacher_fields_trigger
before update on public.submissions
for each row execute function public.protect_submission_teacher_fields();

-- =========================================================
-- Storage
-- =========================================================

insert into storage.buckets (id, name, public)
values ('answer-images', 'answer-images', false)
on conflict (id) do update set public = false;

insert into storage.buckets (id, name, public)
values ('worksheet-pdfs', 'worksheet-pdfs', false)
on conflict (id) do update set public = false;

-- answer-images: teacher all; student only own auth.uid() prefix
 drop policy if exists "teacher read answer images" on storage.objects;
create policy "teacher read answer images"
on storage.objects for select to authenticated
using (bucket_id = 'answer-images' and public.is_teacher());

 drop policy if exists "teacher manage answer images" on storage.objects;
create policy "teacher manage answer images"
on storage.objects for all to authenticated
using (bucket_id = 'answer-images' and public.is_teacher())
with check (bucket_id = 'answer-images' and public.is_teacher());

 drop policy if exists "student read own answer images" on storage.objects;
create policy "student read own answer images"
on storage.objects for select to authenticated
using (
  bucket_id = 'answer-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

 drop policy if exists "student upload own answer images" on storage.objects;
create policy "student upload own answer images"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'answer-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

 drop policy if exists "student update own answer images" on storage.objects;
create policy "student update own answer images"
on storage.objects for update to authenticated
using (
  bucket_id = 'answer-images'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'answer-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

 drop policy if exists "student delete own answer images" on storage.objects;
create policy "student delete own answer images"
on storage.objects for delete to authenticated
using (
  bucket_id = 'answer-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- worksheet-pdfs: teacher manages; students can read PDFs for published assignments in their subjects.
 drop policy if exists "teacher manage worksheet pdfs" on storage.objects;
create policy "teacher manage worksheet pdfs"
on storage.objects for all to authenticated
using (bucket_id = 'worksheet-pdfs' and public.is_teacher())
with check (bucket_id = 'worksheet-pdfs' and public.is_teacher());

 drop policy if exists "student read allowed worksheet pdfs" on storage.objects;
create policy "student read allowed worksheet pdfs"
on storage.objects for select to authenticated
using (
  bucket_id = 'worksheet-pdfs'
  and exists (
    select 1
    from public.assignments a
    join public.students s on s.id = public.current_student_id()
    where a.id::text = (storage.foldername(name))[1]
      and a.published = true
      and s.active = true
      and a.subject = any(s.subjects)
  )
);

-- =========================================================
-- Optional demo assignment
-- Delete this block if you want an empty project.
-- =========================================================

insert into public.assignments (
  subject, title, theme, goal, method, source, prompt, char_limit,
  before_fields, required_elements, answer_flow, teacher_model, published
)
select
  'japanese',
  '9月第1週 日本史論述演習',
  '史料・図像から短字数で説明する：古代貨幣のデザイン比較',
  '古代貨幣の図像的特徴を、史料本文と模式図から短文で説明する。',
  '設問条件を分解する → 必須要素を置く → 字数内で比較を1文にまとめる',
  '北海道大学2025年度 日本史 第1問 問2',
  '和同開珎と富本銭との表面のデザインの相違点を、50字以内で説明しなさい。',
  50,
  '["設問は何を聞いているか","時期・地域・人物"]'::jsonb,
  '["和同開珎は漢字4字の銭文を方孔の周囲に配置する","富本銭は「富本」2字と七曜文を配置する","両者の相違が比較表現で明確になっている"]'::jsonb,
  '和同開珎の特徴 → 対して/一方 → 富本銭の特徴',
  '和同開珎は方孔の周囲に四字を配するが、富本銭は富本二字と七曜文を配する。',
  true
where not exists (select 1 from public.assignments);
